// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dnd_character.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DNDCharacter _$DNDCharacterFromJson(Map<String, dynamic> json) => DNDCharacter(
  name: json['name'] as String? ?? "",
  className: json['className'] as String? ?? "",
  level: json['level'] as String? ?? "",
  race: json['race'] as String? ?? "",
  background: json['background'] as String? ?? "",
  alignment: json['alignment'] as String? ?? "",
  inspiration: json['inspiration'] as String? ?? "",
  proficiencyBonus: json['proficiencyBonus'] as String? ?? "",
  passivePerception: json['passivePerception'] as String? ?? "",
  strength: json['strength'] as String? ?? "",
  strMod: json['strMod'] as String? ?? "",
  dexterity: json['dexterity'] as String? ?? "",
  dexMod: json['dexMod'] as String? ?? "",
  constitution: json['constitution'] as String? ?? "",
  conMod: json['conMod'] as String? ?? "",
  intelligence: json['intelligence'] as String? ?? "",
  intMod: json['intMod'] as String? ?? "",
  wisdom: json['wisdom'] as String? ?? "",
  wisMod: json['wisMod'] as String? ?? "",
  charisma: json['charisma'] as String? ?? "",
  chaMod: json['chaMod'] as String? ?? "",
  strProf: json['strProf'] as bool? ?? false,
  dexProf: json['dexProf'] as bool? ?? false,
  conProf: json['conProf'] as bool? ?? false,
  intProf: json['intProf'] as bool? ?? false,
  wisProf: json['wisProf'] as bool? ?? false,
  chaProf: json['chaProf'] as bool? ?? false,
  acrobaticsProf: json['acrobaticsProf'] as bool? ?? false,
  animalHandlingProf: json['animalHandlingProf'] as bool? ?? false,
  arcanaProf: json['arcanaProf'] as bool? ?? false,
  athleticsProf: json['athleticsProf'] as bool? ?? false,
  deceptionProf: json['deceptionProf'] as bool? ?? false,
  historyProf: json['historyProf'] as bool? ?? false,
  insightProf: json['insightProf'] as bool? ?? false,
  intimidationProf: json['intimidationProf'] as bool? ?? false,
  investigationProf: json['investigationProf'] as bool? ?? false,
  medicineProf: json['medicineProf'] as bool? ?? false,
  natureProf: json['natureProf'] as bool? ?? false,
  perceptionProf: json['perceptionProf'] as bool? ?? false,
  performanceProf: json['performanceProf'] as bool? ?? false,
  persuasionProf: json['persuasionProf'] as bool? ?? false,
  religionProf: json['religionProf'] as bool? ?? false,
  sleightOfHandProf: json['sleightOfHandProf'] as bool? ?? false,
  stealthProf: json['stealthProf'] as bool? ?? false,
  survivalProf: json['survivalProf'] as bool? ?? false,
  armorClass: json['armorClass'] as String? ?? "",
  initiative: json['initiative'] as String? ?? "",
  proficiencies: json['proficiencies'] as String? ?? "",
  featuresTraits: json['featuresTraits'] as String? ?? "",
  speed: json['speed'] as String? ?? "",
  hpCurr: json['hpCurr'] as String? ?? "",
  hpMax: json['hpMax'] as String? ?? "",
  hpTemp: json['hpTemp'] as String? ?? "",
  hitDiceCurr: json['hitDiceCurr'] as String? ?? "",
  hitDiceTotal: json['hitDiceTotal'] as String? ?? "",
  success1: json['success1'] as bool? ?? false,
  success2: json['success2'] as bool? ?? false,
  success3: json['success3'] as bool? ?? false,
  failure1: json['failure1'] as bool? ?? false,
  failure2: json['failure2'] as bool? ?? false,
  failure3: json['failure3'] as bool? ?? false,
  personalityTraits: json['personalityTraits'] as String? ?? "",
  ideals: json['ideals'] as String? ?? "",
  bonds: json['bonds'] as String? ?? "",
  flaws: json['flaws'] as String? ?? "",
  age: json['age'] as String? ?? "",
  height: json['height'] as String? ?? "",
  weight: json['weight'] as String? ?? "",
  eyes: json['eyes'] as String? ?? "",
  skin: json['skin'] as String? ?? "",
  hair: json['hair'] as String? ?? "",
  backstory: json['backstory'] as String? ?? "",
  attacks: (json['attacks'] as List<dynamic>?)
      ?.map((e) => Attack.fromJson(e as Map<String, dynamic>))
      .toList() ?? [],
  cp: json['cp'] as String? ?? "",
  sp: json['sp'] as String? ?? "",
  ep: json['ep'] as String? ?? "",
  gp: json['gp'] as String? ?? "",
  pp: json['pp'] as String? ?? "",
  inventory: json['inventory'] as String? ?? "",
  spellAttackBonus: json['spellAttackBonus'] as String? ?? "",
  spellSaveDC: json['spellSaveDC'] as String? ?? "",
  spellcastingAbility: json['spellcastingAbility'] as String? ?? "",
  spellcastingClass: json['spellcastingClass'] as String? ?? "",
  cantrips: json['cantrips'] == null
      ? null
      : SpellLevelSection.fromJson(json['cantrips'] as Map<String, dynamic>),
  spells1: json['spells1'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells1'] as Map<String, dynamic>),
  spells2: json['spells2'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells2'] as Map<String, dynamic>),
  spells3: json['spells3'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells3'] as Map<String, dynamic>),
  spells4: json['spells4'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells4'] as Map<String, dynamic>),
  spells5: json['spells5'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells5'] as Map<String, dynamic>),
  spells6: json['spells6'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells6'] as Map<String, dynamic>),
  spells7: json['spells7'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells7'] as Map<String, dynamic>),
  spells8: json['spells8'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells8'] as Map<String, dynamic>),
  spells9: json['spells9'] == null
      ? null
      : SpellLevelSection.fromJson(json['spells9'] as Map<String, dynamic>),
  sessionNotes: json['sessionNotes'] as String? ?? "",
);

Map<String, dynamic> _$DNDCharacterToJson(DNDCharacter instance) =>
    <String, dynamic>{
      'name': instance.name,
      'className': instance.className,
      'level': instance.level,
      'race': instance.race,
      'background': instance.background,
      'alignment': instance.alignment,
      'strength': instance.strength,
      'strMod': instance.strMod,
      'dexterity': instance.dexterity,
      'dexMod': instance.dexMod,
      'constitution': instance.constitution,
      'conMod': instance.conMod,
      'intelligence': instance.intelligence,
      'intMod': instance.intMod,
      'wisdom': instance.wisdom,
      'wisMod': instance.wisMod,
      'charisma': instance.charisma,
      'chaMod': instance.chaMod,
      'strProf': instance.strProf,
      'dexProf': instance.dexProf,
      'conProf': instance.conProf,
      'intProf': instance.intProf,
      'wisProf': instance.wisProf,
      'chaProf': instance.chaProf,
      'acrobaticsProf': instance.acrobaticsProf,
      'animalHandlingProf': instance.animalHandlingProf,
      'arcanaProf': instance.arcanaProf,
      'athleticsProf': instance.athleticsProf,
      'deceptionProf': instance.deceptionProf,
      'historyProf': instance.historyProf,
      'insightProf': instance.insightProf,
      'intimidationProf': instance.intimidationProf,
      'investigationProf': instance.investigationProf,
      'medicineProf': instance.medicineProf,
      'natureProf': instance.natureProf,
      'perceptionProf': instance.perceptionProf,
      'performanceProf': instance.performanceProf,
      'persuasionProf': instance.persuasionProf,
      'religionProf': instance.religionProf,
      'sleightOfHandProf': instance.sleightOfHandProf,
      'stealthProf': instance.stealthProf,
      'survivalProf': instance.survivalProf,
      'inspiration': instance.inspiration,
      'proficiencyBonus': instance.proficiencyBonus,
      'passivePerception': instance.passivePerception,
      'proficiencies': instance.proficiencies,
      'featuresTraits': instance.featuresTraits,
      'armorClass': instance.armorClass,
      'initiative': instance.initiative,
      'speed': instance.speed,
      'hpMax': instance.hpMax,
      'hpCurr': instance.hpCurr,
      'hpTemp': instance.hpTemp,
      'success1': instance.success1,
      'success2': instance.success2,
      'success3': instance.success3,
      'failure1': instance.failure1,
      'failure2': instance.failure2,
      'failure3': instance.failure3,
      'hitDiceTotal': instance.hitDiceTotal,
      'hitDiceCurr': instance.hitDiceCurr,
      'personalityTraits': instance.personalityTraits,
      'ideals': instance.ideals,
      'bonds': instance.bonds,
      'flaws': instance.flaws,
      'age': instance.age,
      'height': instance.height,
      'weight': instance.weight,
      'eyes': instance.eyes,
      'skin': instance.skin,
      'hair': instance.hair,
      'backstory': instance.backstory,
      'attacks': instance.attacks.map((e) => e.toJson()).toList(),
      'cp': instance.cp,
      'sp': instance.sp,
      'ep': instance.ep,
      'gp': instance.gp,
      'pp': instance.pp,
      'inventory': instance.inventory,
      'spellcastingClass': instance.spellcastingClass,
      'spellcastingAbility': instance.spellcastingAbility,
      'spellSaveDC': instance.spellSaveDC,
      'spellAttackBonus': instance.spellAttackBonus,
      'cantrips': instance.cantrips.toJson(),
      'spells1': instance.spells1.toJson(),
      'spells2': instance.spells2.toJson(),
      'spells3': instance.spells3.toJson(),
      'spells4': instance.spells4.toJson(),
      'spells5': instance.spells5.toJson(),
      'spells6': instance.spells6.toJson(),
      'spells7': instance.spells7.toJson(),
      'spells8': instance.spells8.toJson(),
      'spells9': instance.spells9.toJson(),
      'sessionNotes': instance.sessionNotes,
    };
